<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose Country</name>
   <tag></tag>
   <elementGuidId>a9a9aa4f-8984-4811-9205-f47e8d22ecc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;dest_country&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='dest_country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-invalid custom-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dest_country</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose CountryIndonesiaPhilippineUnited StateJapanBelgiumUnited KingdomMalaysiaIndiaChineseGermanyKoreaBangladeshCambodiaNepalPakistanSingaporeSri LankaAustriaCyprusVietnamThailandEstoniaFinlandItalyFranceGreeceIrelandLatviaLithuahuaniaLuxembourgMaltaMonacoNetherlandsSlovakiaSloveniaSpainPortugalSan MarinoAustraliaTurkeyAfghanistanAlbaniaAlgeriaAmerican SamoaAndorraAngolaAnguillaAntigua and BarbudaArgentinaArmeniaArubaAzerbaijanBahamas (the)BahrainBarbadosBelarusBelizeBeninBermudaBhutanBolivia (Plurinational State of)Bonaire, Sint Eustatius and SabaBosnia and HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean Territory (the)Brunei DarussalamBulgariaBurkina FasoBurundiCabo VerdeCameroonCanadaCayman Islands (the)Central African Republic (the)ChadChileChristmas IslandCocos (Keeling) Islands (the)ColombiaComoros (the)Congo (the Democratic Republic of the)Congo (the)Cook Islands (the)Costa RicaCroatiaCubaCuraçaoCzechiaCôte d'IvoireDenmarkDjiboutiDominicaDominican Republic (the)EcuadorEgyptEl SalvadorEquatorial GuineaEritreaEthiopiaFalkland Islands (the) [Malvinas]Faroe Islands (the)FijiFrench GuianaFrench PolynesiaFrench Southern Territories (the)GabonGambia (the)GeorgiaGhanaGibraltarGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuineaGuinea-BissauGuyanaHaitiHeard Island and McDonald IslandsHoly See (the)HondurasHong KongHungaryIcelandIran (Islamic Republic of)IraqIsle of ManIsraelJamaicaJerseyJordanKazakhstanKenyaKiribatiKorea (the Democratic People's Republic of)KuwaitKyrgyzstanLao People's Democratic Republic (the)LebanonLesothoLiberiaLibyaLiechtensteinMacaoMadagascarMalawiMaldivesMaliMarshall Islands (the)MartiniqueMauritaniaMauritiusMayotteMexicoMicronesia (Federated States of)Moldova (the Republic of)MongoliaMontenegroMontserratMoroccoMozambiqueMyanmarNamibiaNauruNew CaledoniaNew ZealandNicaraguaNiger (the)NigeriaNiueNorfolk IslandNorthern Mariana Islands (the)NorwayOmanPalauPalestine, State ofPanamaPapua New GuineaParaguayPeruPitcairnPolandPuerto RicoQatarRepublic of North MacedoniaRomaniaRussian Federation (the)RwandaRéunionSaint BarthélemySaint Helena, Ascension and Tristan da CunhaSaint Kitts and NevisSaint LuciaSaint Martin (French part)Saint Pierre and MiquelonSaint Vincent and the GrenadinesSamoaSao Tome and PrincipeSaudi ArabiaSenegalSerbiaSeychellesSierra LeoneSint Maarten (Dutch part)Solomon IslandsSomaliaSouth AfricaSouth Georgia and the South Sandwich IslandsSouth SudanSudan (the)SurinameSvalbard and Jan MayenSwedenSwitzerlandSyrian Arab RepublicTaiwan (Province of China)TajikistanTanzania, United Republic ofTimor-LesteTogoTokelauTongaTrinidad and TobagoTunisiaTurkmenistanTurks and Caicos Islands (the)TuvaluUgandaUkraineUnited Arab Emirates (the)United States Minor Outlying Islands (the)UruguayUzbekistanVanuatuVenezuela (Bolivarian Republic of)Virgin Islands (British)Virgin Islands (U.S.)Wallis and FutunaWestern SaharaYemenZambiaZimbabweÅland Islands</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_body&quot;)/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-md modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;form form-label-right&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-lg-6 text-left&quot;]/select[@class=&quot;form-control is-invalid custom-select&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='dest_country']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='kt_body']/div[6]/div/div/div[2]/form/div/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination Country :'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiary Account Number :'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
